### PR TITLE
feat(hw): Fix sum function

### PR DESCRIPTION
**Pull request by amalitsky**

### CODE REVIEW

**Comment by amalitsky** [comment]
Not sure why package lock got updated.
PR #1 had 14.x node version while this one is using 16.x.
However both had `package-lock` file updated.

**Comment by jsru** [comment]
Добавляю преподавателя (@ShGKme) для код-ревью.

**Review by ShGKme — APPROVED** [review]
Approved👍

**Comment by ShGKme** [comment]
> However both had `package-lock` file updated.

  If packages are installed by `npm install` then any version of npm will install maximum available version compactable with `package.json` files for all dependency tree. Installed versions are fixed in lock file. To install exact versions use `npm ci` instead.

**Comment by amalitsky** [comment]
Got it, thanks! That's different from `yarn install` behavior I think 🤔

**Comment by ShGKme** [comment]
> Got it, thanks! That's different from `yarn install` behavior I think 🤔

`yarn install` works same as `npm ci`, but it requires yarn lock file.

**Pull request merged**
